# Generated by Django 4.2.28 on 2026-02-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
