# Generated by Django 4.2.28 on 2026-02-12 22:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rfp_system', '0002_add_question_hash_for_caching'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('document_processing', 'Document Processing'), ('answer_generation', 'Answer Generation')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failed'), ('REVOKED', 'Revoked')], default='PENDING', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('total_steps', models.IntegerField(default=1)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rfp_system.document')),
                ('rfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rfp_system.rfp')),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
